
export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const FETCH_PROJECTS_START='FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS='FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL='FETCH_PROJECTS_FAIL';

export const NEW_PROJECT_START='NEW_PROJECT_START';
export const NEW_PROJECT_SUCCESS='NEW_PROJECT_SUCCESS';
export const NEW_PROJECT_FAIL='NEW_PROJECT_FAIL';
export const NEW_PROJECT_CLEAR='NEW_PROJECT_CLEAR';

export const FETCH_DETAILS_START='FETCH_DETAILS_START';
export const FETCH_DETAILS_FAIL='FETCH_DETAILS_FAIL';
export const FETCH_DETAILS_SUCCESS='FETCH_DETAILS_SUCCESS';
